//id (auto unique)
//title of service (list service page)
//availability (list service page)
//industry (fk) (list service page)
//freelancer(fk) (list service page)
//price (list service page)
//hourly cost (list service page)
//short description(list service page)
